### ISSUE TITLE
Problemas com a declaração do CPF.

### ISSUE THREAD

**Issue by Murdev29** [cami-la/mentoria_GFT_START_5_23052022#2]
Bom dia!

 No Exercício de cálculo de salários, dos vendedores e consultores, foi declarado o CPF como sendo do tipo "LONG", porém na hora de testar o código ele deu um erro, pois o CPF que eu passei iniciava com "0", ele não aceitou assim, como resolveria a título de curiosidade, e desculpe minha ignorância.

**Comment by cami-la** [comment]
> Bom dia!
> 
> No Exercício de cálculo de salários, dos vendedores e consultores, foi declarado o CPF como sendo do tipo "LONG", porém na hora de testar o código ele deu um erro, pois o CPF que eu passei iniciava com "0", ele não aceitou assim, como resolveria a título de curiosidade, e desculpe minha ignorância.

Isso aí, @Murdev29. Sempre utilizo o tipo `String`, mas esse exercício não fui eu quem fiz, aí peguei os atributos já tipados.
Seu questionamento é muito inteligente, mostra que você está pensando nos possíveis cenários de aplicação.

Mas como nosso amigo, @mattferraz explicou muito bem no comentário abaixo, no nosso cenário atual, é indiferente ser `Long` ou `String`, já que não vamos fazer manipulação com esse CPF.

Parabéns, meninos! <3

**Comment by cami-la** [comment]
> Zeros à esquerda são desconsiderados em tipos numéricos. Se tu queres que teu CPF comece com 0, ao invés de utilizar o tipo long usa String. Como nesse exercício tu não vai realizar nenhuma operação matemática com o CPF, então não tem problema utilizar String.

É isso mesmo!. Não tiro nenhuma vírgula do seu comentário, @mattferraz. 
Só complementando, o tipo `String` é muito usado no CPF para colocar máscaras, tipo assim 123.456.789-00. Esses "." e o hífen "-" nós podemos aplicar com `Regex`. Aí precisa ser do tipo `String`.
Como não foi necessário máscara e nem aplicações matemáticas, o tipo `Long` serve também!

Parabéns e muito obrigada por ajudar o colega e compartilhar seu conhecimento.
Precisando, fico à disposição!

**Comment by cami-la** [comment]
> > Zeros à esquerda são desconsiderados em tipos numéricos. Se tu queres que teu CPF comece com 0, ao invés de utilizar o tipo long usa String. Como nesse exercício tu não vai realizar nenhuma operação matemática com o CPF, então não tem problema utilizar String.
> 
> É isso mesmo!. Não tiro nenhuma vírgula do seu comentário, @mattferraz. Só complementando, o tipo String é muito usado no CPF para colocar máscaras, tipo assim 123.456.789-00. Esses "." e o hífen "-" nós podemos aplicar com Regex. Aí precisa ser do tipo String. Como não foi necessário máscara e nem aplicações matemáticas, o tipo Long serve também!
> 
> Parabéns e muito obrigada por ajudar o colega e compartilhar seu conhecimento. Precisando, fico à disposição!
