### ISSUE TITLE
Desafio do Macaquinho

### ISSUE THREAD

**Issue by hanakathy** [cami-la/mentoria_GFT_START_5_23052022#5]
No caso do `bucho.remove` eu utilizei direto o número do índice. Ficando assim: ` bucho.remove(0)` e funcionou.

Tem alguma diferença do `bucho.remove(bucho.get(0))`?

**Comment by cami-la** [comment]
Oi, Kathy. Bom dia!
Muito boa sua observação.

O método `remove()` ele tem algumas sobrecargas, logo ele pode receber um index (que foi da forma que você fez) e um objeto (que foi da forma que eu fiz). 

Uma das diferenças das chamadas deste método é o retorno:

1. Quando utilizamos o `list.remove(int index)`, o retorno será uma `String` nos valores: 1 (se o elemento foi removido) e -1 (se o elemento não foi removido e provavelmente lançará uma Exception, dá uma olhadinha na documentação e vê as Exceptions).
![Screenshot from 2022-06-07 11-38-20](https://user-images.githubusercontent.com/64323124/172408962-690a02fb-1368-4b4c-8441-bebb2c51e0cc.png)

2. Quando utilizamos o `list.remove(Object o)` o retorno será um `boolean` nos valores: true (se o elemento foi removido) e false (se o elemento não foi removido e provavelmente não lançará Exception, dá uma olhadinha na documentação e vê as Exceptions). 
![Screenshot from 2022-06-07 12-04-56](https://user-images.githubusercontent.com/64323124/172414908-84dcb10f-9dad-47df-aa2c-d015cf791f6a.png)

Mas e aí? Quando usar cada qual?

- Se você souber a posição exata do elemento que você deseja remover, usa a primeira oção.
- Caso você conheça o elemento e não sabe em que posição ele se encontra, usa a segunda opção.
- E no nosso caso, sabemos tanto a posição, quanto o elemento, aí podemos utilizar qualquer uma das sobrecargas. (:

Fico à disposição!

**Comment by hanakathy** [comment]
Entendi. Ficou muito claro com a sua explicação.

Obrigada, Camila! <3
